# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

baseurl: ""
url: "https://brandoncaples.com"
logo: "https://pbs.twimg.com/profile_images/1482576665838600195/KmXL8nh7_400x400.jpg"
permalink: /:categories/:year/:title

# AUTHOR
author:
  name: "Brandon Caples"
  email: "brandon.caples@gmail.com"
  phone: "4232815150"

# META
meta:
  title: "Brandon Caples"
  description: "I am a marketing professional working at the intersection of strategy and technology."

# SOCIALS
social:
  facebook:
  github: capncapes
  upwork:
  alignable: 15533029
  goodreads: caples
  bluesky: "bcaples.bsky.social"
  instagram:
  linkedin: "https://www.linkedin.com/in/brandoncaples"
  pinterest:
  reddit:
  trailhead: "bcaples"
  stack_exchange:
  tiktok:
  twitter:
    username:
    id: 106212276
  youtube:

# SCRIPTS
scripts:
  ga4: G-K2XZK7JBSM
  gtm: GTM-WWRT8C9
  squeaky:
  google_fonts: "Roboto:300,600|Roboto+Condensed:700|Playfair+Display:900"
  disqus_shortname:
  katex: true

# COLLECTIONS
collections:
  book_reviews:
    output: true
    permalink: /book-reviews/:title
  portfolio_email:
    output: true
    permalink: /:title
  portfolio_web:
    output: true
    permalink: /:title
  portfolio_tags:
    permalink: /portfolio/tags/:name/
    output: true
  ads:
    output: false

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
highlighter: rouge
input: GFM
timezone: America/New_York

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

require: ./filters.rb
theme: jekyll-theme-leap-day