# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

baseurl: ""
url: "https://brandoncaples.com"
logo: "https://pbs.twimg.com/profile_images/1482576665838600195/KmXL8nh7_400x400.jpg"
permalink: /:categories/:year/:title

# AUTHOR
author:
  name: "Brandon Caples"
  email:
  phone:

# META
meta:
  title: "Brandon Caples"
  description: "I am a marketing technologist working at the intersection of strategy and technology."

# SOCIALS
social:
  facebook:
  github: capncapes
  upwork: "https://www.upwork.com/freelancers/~01c83238ef648b4309"
  goodreads: caples
  instagram:
  linkedin: "https://www.linkedin.com/in/brandoncaples"
  pinterest:
  reddit:
  trailhead: "bcaples"
  stack_exchange:
  tiktok:
  twitter:
    username:
    id: 106212276
  youtube:

# SCRIPTS
scripts:
  ga4: G-K2XZK7JBSM
  gtm: GTM-WWRT8C9
  squeaky: f94d0c0f-89b6-4cc0-a52c-e05932e7a59d
  google_fonts: "Roboto:300,600|Roboto+Condensed:700|Playfair+Display:900"
  disqus_shortname:
  katex: true # Enable if using math markup

# PAGINATION
# paginate: 3
# paginate_path: "faith/:num"

# paginate: 4
# pagination:
#   - paginate:
#     path: /faith/:num
#     per_page: 3
#   - paginate:
#     path: /martech/:num
#     per_page: 2

# COLLECTIONS
collections:
  book_reviews:
    output: true
    permalink: /book-reviews/:title
  ads:
    output: false

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
highlighter: rouge
input: GFM
timezone: America/New_York

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

require: ./filters.rb
theme: jekyll-theme-leap-day